---
session_name: default
start_directory: ~/
windows:
  - focus: true
    panes:
      - null
  - window_name: sdjournal
    window_index: 9
    panes:
      - shell_command:
          - exec sudo journalctl --follow
